### ISSUE TITLE
photo assets

### ISSUE THREAD

**Issue by dylanreedx** [carbondesigned/CityCyclery#4]
Gather and add assets for the following:

- [x] Logo variations (logomark, wordmark, etc.)
- [x] Favicon
- [x] Hero image
- [ ] Brand logos or product photos 
- [ ] About  page
- [ ] Stylized map for contact page

Not sure if we want to keep the brand photos on the home page consistent with the ones on the brand page

Also may need to add something to the services page

**Comment by langleynick** [comment]
services page may need a hero image- or we can refactor the cards for Installs & Adjustments to allow space for an image next to it.

**Comment by amyers0217** [comment]
I put the logo files in our Teams folder. There are a couple options in there I think
