### ISSUE TITLE
Fix home page brands section

### ISSUE THREAD

**Issue by aSouchereau** [carbondesigned/CityCyclery#42]
The brands section is overflowing the intended width on mobile, causing a horizontal scroll bar

**Comment by dylanreedx** [comment]
- the brands are no longer strolling (but we could change this, where there is only a few brands?)
- brand cards are different heights because of the content

**Comment by aSouchereau** [comment]
So heights are fixed, I used the line-clamp plugin to limit the description to 5 lines.

Since there's only 3 house brands now, I changed the layout to use grids, 3 cols on large, 2 on med, and full width on small. Only issue I see is that on smaller widths when it wraps to 1 col, it makes the entire brands section pretty tall. To solve this we could change the heights of each card on smaller screens to try to condense it a little bit.

I've also tested it using flexbox with no-wrap and horizontal scrolling, and it seems to work fine. However I think going the grid route would be better for UX.

Just want to see what everyone thinks of each option before I start working on it

**Comment by aSouchereau** [comment]
Also, I was wondering if we should keep the card buttons as contact buttons. We already have 3 other contact buttons on that page, so I think it would be better if they linked directly to each brands site.

**Comment by amyers0217** [comment]
Yeah, I think we should get rid of the contact buttons for the brands and just have them link to the brand sites. If the grid works best and we can just add in CSS to change with different screen sizes I think that would be good!

**Comment by langleynick** [comment]
Works for me!

**Comment by langleynick** [comment]
Maybe we can refactor the cards to utilize the BrandCardComponent then> since it has a button to link to the page already

**Comment by aSouchereau** [comment]
Sounds good, I'll do that
